# fly.toml app configuration file generated for crypto-exchange-hidden-rain-3956 on 2024-08-28T07:55:16+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crypto-exchange-hidden-rain-3956'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
